# Generated by Django 3.1.1 on 2020-09-17 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clan',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
